# Generated by Django 4.2.7 on 2023-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavLyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(blank=True, db_column='FAV_ID', null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='USER_ID', null=True)),
                ('song_id', models.IntegerField(blank=True, db_column='SONG_ID', null=True)),
            ],
            options={
                'db_table': 'FAV_LYRICS',
                'managed': False,
            },
        ),
    ]
